// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsFlutterMessage(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsFlutterMessage(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsFlutterMessage(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashFlutterMessage(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashFlutterMessage(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashFlutterMessage(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum BrandingTypeMessage: Int {
  case light = 0
  case dark = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConfigurationMessage: Hashable {
  var organization: String
  var applicationId: Int64
  var applicationSecret: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConfigurationMessage? {
    let organization = pigeonVar_list[0] as! String
    let applicationId = pigeonVar_list[1] as! Int64
    let applicationSecret = pigeonVar_list[2] as! String

    return ConfigurationMessage(
      organization: organization,
      applicationId: applicationId,
      applicationSecret: applicationSecret
    )
  }
  func toList() -> [Any?] {
    return [
      organization,
      applicationId,
      applicationSecret,
    ]
  }
  static func == (lhs: ConfigurationMessage, rhs: ConfigurationMessage) -> Bool {
    return deepEqualsFlutterMessage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterMessage(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UserMessage: Hashable {
  var id: String
  var name: String? = nil
  var email: String? = nil
  var phone: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UserMessage? {
    let id = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let email: String? = nilOrValue(pigeonVar_list[2])
    let phone: String? = nilOrValue(pigeonVar_list[3])

    return UserMessage(
      id: id,
      name: name,
      email: email,
      phone: phone
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      email,
      phone,
    ]
  }
  static func == (lhs: UserMessage, rhs: UserMessage) -> Bool {
    return deepEqualsFlutterMessage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterMessage(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AvatarThemeMessage: Hashable {
  var useDefaultAvatarColors: Bool
  var placeholderBackgroundColor: Int64? = nil
  var placeholderTextColor: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AvatarThemeMessage? {
    let useDefaultAvatarColors = pigeonVar_list[0] as! Bool
    let placeholderBackgroundColor: Int64? = nilOrValue(pigeonVar_list[1])
    let placeholderTextColor: Int64? = nilOrValue(pigeonVar_list[2])

    return AvatarThemeMessage(
      useDefaultAvatarColors: useDefaultAvatarColors,
      placeholderBackgroundColor: placeholderBackgroundColor,
      placeholderTextColor: placeholderTextColor
    )
  }
  func toList() -> [Any?] {
    return [
      useDefaultAvatarColors,
      placeholderBackgroundColor,
      placeholderTextColor,
    ]
  }
  static func == (lhs: AvatarThemeMessage, rhs: AvatarThemeMessage) -> Bool {
    return deepEqualsFlutterMessage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterMessage(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MessageAreaThemeMessage: Hashable {
  var backgroundColor: Int64? = nil
  var inputOutlineColor: Int64? = nil
  var inputFieldTextColor: Int64? = nil
  var inputFieldTextHintColor: Int64? = nil
  var messageMenuBackgroundColor: Int64? = nil
  var messageMenuTextColor: Int64? = nil
  var messageMenuSummaryTextColor: Int64? = nil
  var messageMenuIconColor: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MessageAreaThemeMessage? {
    let backgroundColor: Int64? = nilOrValue(pigeonVar_list[0])
    let inputOutlineColor: Int64? = nilOrValue(pigeonVar_list[1])
    let inputFieldTextColor: Int64? = nilOrValue(pigeonVar_list[2])
    let inputFieldTextHintColor: Int64? = nilOrValue(pigeonVar_list[3])
    let messageMenuBackgroundColor: Int64? = nilOrValue(pigeonVar_list[4])
    let messageMenuTextColor: Int64? = nilOrValue(pigeonVar_list[5])
    let messageMenuSummaryTextColor: Int64? = nilOrValue(pigeonVar_list[6])
    let messageMenuIconColor: Int64? = nilOrValue(pigeonVar_list[7])

    return MessageAreaThemeMessage(
      backgroundColor: backgroundColor,
      inputOutlineColor: inputOutlineColor,
      inputFieldTextColor: inputFieldTextColor,
      inputFieldTextHintColor: inputFieldTextHintColor,
      messageMenuBackgroundColor: messageMenuBackgroundColor,
      messageMenuTextColor: messageMenuTextColor,
      messageMenuSummaryTextColor: messageMenuSummaryTextColor,
      messageMenuIconColor: messageMenuIconColor
    )
  }
  func toList() -> [Any?] {
    return [
      backgroundColor,
      inputOutlineColor,
      inputFieldTextColor,
      inputFieldTextHintColor,
      messageMenuBackgroundColor,
      messageMenuTextColor,
      messageMenuSummaryTextColor,
      messageMenuIconColor,
    ]
  }
  static func == (lhs: MessageAreaThemeMessage, rhs: MessageAreaThemeMessage) -> Bool {
    return deepEqualsFlutterMessage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterMessage(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChatAreaThemeMessage: Hashable {
  var incomingBubbleTextColor: Int64? = nil
  var outcomingBubbleTextColor: Int64? = nil
  var incomingBubbleColor: Int64? = nil
  var outcomingBubbleColor: Int64? = nil
  var backgroundColor: Int64? = nil
  var brandingType: BrandingTypeMessage
  var incomingCodeBackgroundColor: Int64? = nil
  var outcomingCodeBackgroundColor: Int64? = nil
  var incomingCodeTextColor: Int64? = nil
  var outcomingCodeTextColor: Int64? = nil
  var incomingBlockQuoteColor: Int64? = nil
  var outcomingBlockQuoteColor: Int64? = nil
  var incomingFileTextColor: Int64? = nil
  var outcomingFileTextColor: Int64? = nil
  var authorNameColor: Int64? = nil
  var systemMessageColor: Int64? = nil
  var timeTextColor: Int64? = nil
  var progressViewsColor: Int64? = nil
  var chatBackgroundColor: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChatAreaThemeMessage? {
    let incomingBubbleTextColor: Int64? = nilOrValue(pigeonVar_list[0])
    let outcomingBubbleTextColor: Int64? = nilOrValue(pigeonVar_list[1])
    let incomingBubbleColor: Int64? = nilOrValue(pigeonVar_list[2])
    let outcomingBubbleColor: Int64? = nilOrValue(pigeonVar_list[3])
    let backgroundColor: Int64? = nilOrValue(pigeonVar_list[4])
    let brandingType = pigeonVar_list[5] as! BrandingTypeMessage
    let incomingCodeBackgroundColor: Int64? = nilOrValue(pigeonVar_list[6])
    let outcomingCodeBackgroundColor: Int64? = nilOrValue(pigeonVar_list[7])
    let incomingCodeTextColor: Int64? = nilOrValue(pigeonVar_list[8])
    let outcomingCodeTextColor: Int64? = nilOrValue(pigeonVar_list[9])
    let incomingBlockQuoteColor: Int64? = nilOrValue(pigeonVar_list[10])
    let outcomingBlockQuoteColor: Int64? = nilOrValue(pigeonVar_list[11])
    let incomingFileTextColor: Int64? = nilOrValue(pigeonVar_list[12])
    let outcomingFileTextColor: Int64? = nilOrValue(pigeonVar_list[13])
    let authorNameColor: Int64? = nilOrValue(pigeonVar_list[14])
    let systemMessageColor: Int64? = nilOrValue(pigeonVar_list[15])
    let timeTextColor: Int64? = nilOrValue(pigeonVar_list[16])
    let progressViewsColor: Int64? = nilOrValue(pigeonVar_list[17])
    let chatBackgroundColor: Int64? = nilOrValue(pigeonVar_list[18])

    return ChatAreaThemeMessage(
      incomingBubbleTextColor: incomingBubbleTextColor,
      outcomingBubbleTextColor: outcomingBubbleTextColor,
      incomingBubbleColor: incomingBubbleColor,
      outcomingBubbleColor: outcomingBubbleColor,
      backgroundColor: backgroundColor,
      brandingType: brandingType,
      incomingCodeBackgroundColor: incomingCodeBackgroundColor,
      outcomingCodeBackgroundColor: outcomingCodeBackgroundColor,
      incomingCodeTextColor: incomingCodeTextColor,
      outcomingCodeTextColor: outcomingCodeTextColor,
      incomingBlockQuoteColor: incomingBlockQuoteColor,
      outcomingBlockQuoteColor: outcomingBlockQuoteColor,
      incomingFileTextColor: incomingFileTextColor,
      outcomingFileTextColor: outcomingFileTextColor,
      authorNameColor: authorNameColor,
      systemMessageColor: systemMessageColor,
      timeTextColor: timeTextColor,
      progressViewsColor: progressViewsColor,
      chatBackgroundColor: chatBackgroundColor
    )
  }
  func toList() -> [Any?] {
    return [
      incomingBubbleTextColor,
      outcomingBubbleTextColor,
      incomingBubbleColor,
      outcomingBubbleColor,
      backgroundColor,
      brandingType,
      incomingCodeBackgroundColor,
      outcomingCodeBackgroundColor,
      incomingCodeTextColor,
      outcomingCodeTextColor,
      incomingBlockQuoteColor,
      outcomingBlockQuoteColor,
      incomingFileTextColor,
      outcomingFileTextColor,
      authorNameColor,
      systemMessageColor,
      timeTextColor,
      progressViewsColor,
      chatBackgroundColor,
    ]
  }
  static func == (lhs: ChatAreaThemeMessage, rhs: ChatAreaThemeMessage) -> Bool {
    return deepEqualsFlutterMessage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterMessage(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PreChatThemeMessage: Hashable {
  var inputFieldTextColor: Int64? = nil
  var inputFieldTextHintColor: Int64? = nil
  var backgroundColor: Int64? = nil
  var messageBackgroundColor: Int64? = nil
  var messageTextColor: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreChatThemeMessage? {
    let inputFieldTextColor: Int64? = nilOrValue(pigeonVar_list[0])
    let inputFieldTextHintColor: Int64? = nilOrValue(pigeonVar_list[1])
    let backgroundColor: Int64? = nilOrValue(pigeonVar_list[2])
    let messageBackgroundColor: Int64? = nilOrValue(pigeonVar_list[3])
    let messageTextColor: Int64? = nilOrValue(pigeonVar_list[4])

    return PreChatThemeMessage(
      inputFieldTextColor: inputFieldTextColor,
      inputFieldTextHintColor: inputFieldTextHintColor,
      backgroundColor: backgroundColor,
      messageBackgroundColor: messageBackgroundColor,
      messageTextColor: messageTextColor
    )
  }
  func toList() -> [Any?] {
    return [
      inputFieldTextColor,
      inputFieldTextHintColor,
      backgroundColor,
      messageBackgroundColor,
      messageTextColor,
    ]
  }
  static func == (lhs: PreChatThemeMessage, rhs: PreChatThemeMessage) -> Bool {
    return deepEqualsFlutterMessage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterMessage(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ToolbarAreaThemeMessage: Hashable {
  var backgroundColor: Int64? = nil
  var statusBarColor: Int64? = nil
  var outlineColor: Int64? = nil
  var agentsTextColor: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ToolbarAreaThemeMessage? {
    let backgroundColor: Int64? = nilOrValue(pigeonVar_list[0])
    let statusBarColor: Int64? = nilOrValue(pigeonVar_list[1])
    let outlineColor: Int64? = nilOrValue(pigeonVar_list[2])
    let agentsTextColor: Int64? = nilOrValue(pigeonVar_list[3])

    return ToolbarAreaThemeMessage(
      backgroundColor: backgroundColor,
      statusBarColor: statusBarColor,
      outlineColor: outlineColor,
      agentsTextColor: agentsTextColor
    )
  }
  func toList() -> [Any?] {
    return [
      backgroundColor,
      statusBarColor,
      outlineColor,
      agentsTextColor,
    ]
  }
  static func == (lhs: ToolbarAreaThemeMessage, rhs: ToolbarAreaThemeMessage) -> Bool {
    return deepEqualsFlutterMessage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterMessage(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ThemeMessage: Hashable {
  var primaryColor: Int64? = nil
  var toolbarAreaTheme: ToolbarAreaThemeMessage? = nil
  var chatAreaTheme: ChatAreaThemeMessage? = nil
  var messageAreaTheme: MessageAreaThemeMessage? = nil
  var preChatTheme: PreChatThemeMessage? = nil
  var avatarTheme: AvatarThemeMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ThemeMessage? {
    let primaryColor: Int64? = nilOrValue(pigeonVar_list[0])
    let toolbarAreaTheme: ToolbarAreaThemeMessage? = nilOrValue(pigeonVar_list[1])
    let chatAreaTheme: ChatAreaThemeMessage? = nilOrValue(pigeonVar_list[2])
    let messageAreaTheme: MessageAreaThemeMessage? = nilOrValue(pigeonVar_list[3])
    let preChatTheme: PreChatThemeMessage? = nilOrValue(pigeonVar_list[4])
    let avatarTheme: AvatarThemeMessage? = nilOrValue(pigeonVar_list[5])

    return ThemeMessage(
      primaryColor: primaryColor,
      toolbarAreaTheme: toolbarAreaTheme,
      chatAreaTheme: chatAreaTheme,
      messageAreaTheme: messageAreaTheme,
      preChatTheme: preChatTheme,
      avatarTheme: avatarTheme
    )
  }
  func toList() -> [Any?] {
    return [
      primaryColor,
      toolbarAreaTheme,
      chatAreaTheme,
      messageAreaTheme,
      preChatTheme,
      avatarTheme,
    ]
  }
  static func == (lhs: ThemeMessage, rhs: ThemeMessage) -> Bool {
    return deepEqualsFlutterMessage(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFlutterMessage(value: toList(), hasher: &hasher)
  }
}

private class FlutterMessagePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BrandingTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return ConfigurationMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return UserMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return AvatarThemeMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return MessageAreaThemeMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return ChatAreaThemeMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return PreChatThemeMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return ToolbarAreaThemeMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return ThemeMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterMessagePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BrandingTypeMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ConfigurationMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? UserMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AvatarThemeMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MessageAreaThemeMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ChatAreaThemeMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PreChatThemeMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ToolbarAreaThemeMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? ThemeMessage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterMessagePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterMessagePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterMessagePigeonCodecWriter(data: data)
  }
}

class FlutterMessagePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterMessagePigeonCodec(readerWriter: FlutterMessagePigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterHelpCrunchApi {
  func initialize(configuration: ConfigurationMessage, user: UserMessage, theme: ThemeMessage?) throws
  func updateUser(user: UserMessage) throws
  func showChatScreen() throws -> Bool
  func sendMessage(message: String, isForceNewChat: Bool) throws
  func logout() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterHelpCrunchApiSetup {
  static var codec: FlutterStandardMessageCodec { FlutterMessagePigeonCodec.shared }
  /// Sets up an instance of `FlutterHelpCrunchApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterHelpCrunchApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! ConfigurationMessage
        let userArg = args[1] as! UserMessage
        let themeArg: ThemeMessage? = nilOrValue(args[2])
        do {
          try api.initialize(configuration: configurationArg, user: userArg, theme: themeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let updateUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.updateUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateUserChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userArg = args[0] as! UserMessage
        do {
          try api.updateUser(user: userArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateUserChannel.setMessageHandler(nil)
    }
    let showChatScreenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.showChatScreen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChatScreenChannel.setMessageHandler { _, reply in
        do {
          let result = try api.showChatScreen()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showChatScreenChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        let isForceNewChatArg = args[1] as! Bool
        do {
          try api.sendMessage(message: messageArg, isForceNewChat: isForceNewChatArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    let logoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.logout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logoutChannel.setMessageHandler { _, reply in
        do {
          try api.logout()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      logoutChannel.setMessageHandler(nil)
    }
  }
}
