// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object FlutterMessagePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class BrandingTypeMessage(val raw: Int) {
  LIGHT(0),
  DARK(1);

  companion object {
    fun ofRaw(raw: Int): BrandingTypeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConfigurationMessage (
  val organization: String,
  val applicationId: Long,
  val applicationSecret: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfigurationMessage {
      val organization = pigeonVar_list[0] as String
      val applicationId = pigeonVar_list[1] as Long
      val applicationSecret = pigeonVar_list[2] as String
      return ConfigurationMessage(organization, applicationId, applicationSecret)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      organization,
      applicationId,
      applicationSecret,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ConfigurationMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UserMessage (
  val id: String,
  val name: String? = null,
  val email: String? = null,
  val phone: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserMessage {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val email = pigeonVar_list[2] as String?
      val phone = pigeonVar_list[3] as String?
      return UserMessage(id, name, email, phone)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      email,
      phone,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AvatarThemeMessage (
  val useDefaultAvatarColors: Boolean,
  val placeholderBackgroundColor: Long? = null,
  val placeholderTextColor: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AvatarThemeMessage {
      val useDefaultAvatarColors = pigeonVar_list[0] as Boolean
      val placeholderBackgroundColor = pigeonVar_list[1] as Long?
      val placeholderTextColor = pigeonVar_list[2] as Long?
      return AvatarThemeMessage(useDefaultAvatarColors, placeholderBackgroundColor, placeholderTextColor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      useDefaultAvatarColors,
      placeholderBackgroundColor,
      placeholderTextColor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AvatarThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MessageAreaThemeMessage (
  val backgroundColor: Long? = null,
  val inputOutlineColor: Long? = null,
  val inputFieldTextColor: Long? = null,
  val inputFieldTextHintColor: Long? = null,
  val messageMenuBackgroundColor: Long? = null,
  val messageMenuTextColor: Long? = null,
  val messageMenuSummaryTextColor: Long? = null,
  val messageMenuIconColor: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageAreaThemeMessage {
      val backgroundColor = pigeonVar_list[0] as Long?
      val inputOutlineColor = pigeonVar_list[1] as Long?
      val inputFieldTextColor = pigeonVar_list[2] as Long?
      val inputFieldTextHintColor = pigeonVar_list[3] as Long?
      val messageMenuBackgroundColor = pigeonVar_list[4] as Long?
      val messageMenuTextColor = pigeonVar_list[5] as Long?
      val messageMenuSummaryTextColor = pigeonVar_list[6] as Long?
      val messageMenuIconColor = pigeonVar_list[7] as Long?
      return MessageAreaThemeMessage(backgroundColor, inputOutlineColor, inputFieldTextColor, inputFieldTextHintColor, messageMenuBackgroundColor, messageMenuTextColor, messageMenuSummaryTextColor, messageMenuIconColor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      backgroundColor,
      inputOutlineColor,
      inputFieldTextColor,
      inputFieldTextHintColor,
      messageMenuBackgroundColor,
      messageMenuTextColor,
      messageMenuSummaryTextColor,
      messageMenuIconColor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MessageAreaThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ChatAreaThemeMessage (
  val incomingBubbleTextColor: Long? = null,
  val outcomingBubbleTextColor: Long? = null,
  val incomingBubbleColor: Long? = null,
  val outcomingBubbleColor: Long? = null,
  val backgroundColor: Long? = null,
  val brandingType: BrandingTypeMessage,
  val incomingCodeBackgroundColor: Long? = null,
  val outcomingCodeBackgroundColor: Long? = null,
  val incomingCodeTextColor: Long? = null,
  val outcomingCodeTextColor: Long? = null,
  val incomingBlockQuoteColor: Long? = null,
  val outcomingBlockQuoteColor: Long? = null,
  val incomingFileTextColor: Long? = null,
  val outcomingFileTextColor: Long? = null,
  val authorNameColor: Long? = null,
  val systemMessageColor: Long? = null,
  val timeTextColor: Long? = null,
  val progressViewsColor: Long? = null,
  val chatBackgroundColor: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ChatAreaThemeMessage {
      val incomingBubbleTextColor = pigeonVar_list[0] as Long?
      val outcomingBubbleTextColor = pigeonVar_list[1] as Long?
      val incomingBubbleColor = pigeonVar_list[2] as Long?
      val outcomingBubbleColor = pigeonVar_list[3] as Long?
      val backgroundColor = pigeonVar_list[4] as Long?
      val brandingType = pigeonVar_list[5] as BrandingTypeMessage
      val incomingCodeBackgroundColor = pigeonVar_list[6] as Long?
      val outcomingCodeBackgroundColor = pigeonVar_list[7] as Long?
      val incomingCodeTextColor = pigeonVar_list[8] as Long?
      val outcomingCodeTextColor = pigeonVar_list[9] as Long?
      val incomingBlockQuoteColor = pigeonVar_list[10] as Long?
      val outcomingBlockQuoteColor = pigeonVar_list[11] as Long?
      val incomingFileTextColor = pigeonVar_list[12] as Long?
      val outcomingFileTextColor = pigeonVar_list[13] as Long?
      val authorNameColor = pigeonVar_list[14] as Long?
      val systemMessageColor = pigeonVar_list[15] as Long?
      val timeTextColor = pigeonVar_list[16] as Long?
      val progressViewsColor = pigeonVar_list[17] as Long?
      val chatBackgroundColor = pigeonVar_list[18] as Long?
      return ChatAreaThemeMessage(incomingBubbleTextColor, outcomingBubbleTextColor, incomingBubbleColor, outcomingBubbleColor, backgroundColor, brandingType, incomingCodeBackgroundColor, outcomingCodeBackgroundColor, incomingCodeTextColor, outcomingCodeTextColor, incomingBlockQuoteColor, outcomingBlockQuoteColor, incomingFileTextColor, outcomingFileTextColor, authorNameColor, systemMessageColor, timeTextColor, progressViewsColor, chatBackgroundColor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      incomingBubbleTextColor,
      outcomingBubbleTextColor,
      incomingBubbleColor,
      outcomingBubbleColor,
      backgroundColor,
      brandingType,
      incomingCodeBackgroundColor,
      outcomingCodeBackgroundColor,
      incomingCodeTextColor,
      outcomingCodeTextColor,
      incomingBlockQuoteColor,
      outcomingBlockQuoteColor,
      incomingFileTextColor,
      outcomingFileTextColor,
      authorNameColor,
      systemMessageColor,
      timeTextColor,
      progressViewsColor,
      chatBackgroundColor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ChatAreaThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreChatThemeMessage (
  val inputFieldTextColor: Long? = null,
  val inputFieldTextHintColor: Long? = null,
  val backgroundColor: Long? = null,
  val messageBackgroundColor: Long? = null,
  val messageTextColor: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreChatThemeMessage {
      val inputFieldTextColor = pigeonVar_list[0] as Long?
      val inputFieldTextHintColor = pigeonVar_list[1] as Long?
      val backgroundColor = pigeonVar_list[2] as Long?
      val messageBackgroundColor = pigeonVar_list[3] as Long?
      val messageTextColor = pigeonVar_list[4] as Long?
      return PreChatThemeMessage(inputFieldTextColor, inputFieldTextHintColor, backgroundColor, messageBackgroundColor, messageTextColor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      inputFieldTextColor,
      inputFieldTextHintColor,
      backgroundColor,
      messageBackgroundColor,
      messageTextColor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PreChatThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ToolbarAreaThemeMessage (
  val backgroundColor: Long? = null,
  val statusBarColor: Long? = null,
  val outlineColor: Long? = null,
  val agentsTextColor: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ToolbarAreaThemeMessage {
      val backgroundColor = pigeonVar_list[0] as Long?
      val statusBarColor = pigeonVar_list[1] as Long?
      val outlineColor = pigeonVar_list[2] as Long?
      val agentsTextColor = pigeonVar_list[3] as Long?
      return ToolbarAreaThemeMessage(backgroundColor, statusBarColor, outlineColor, agentsTextColor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      backgroundColor,
      statusBarColor,
      outlineColor,
      agentsTextColor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ToolbarAreaThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ThemeMessage (
  val primaryColor: Long,
  val toolbarAreaTheme: ToolbarAreaThemeMessage? = null,
  val chatAreaTheme: ChatAreaThemeMessage? = null,
  val messageAreaTheme: MessageAreaThemeMessage? = null,
  val preChatTheme: PreChatThemeMessage? = null,
  val avatarTheme: AvatarThemeMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ThemeMessage {
      val primaryColor = pigeonVar_list[0] as Long
      val toolbarAreaTheme = pigeonVar_list[1] as ToolbarAreaThemeMessage?
      val chatAreaTheme = pigeonVar_list[2] as ChatAreaThemeMessage?
      val messageAreaTheme = pigeonVar_list[3] as MessageAreaThemeMessage?
      val preChatTheme = pigeonVar_list[4] as PreChatThemeMessage?
      val avatarTheme = pigeonVar_list[5] as AvatarThemeMessage?
      return ThemeMessage(primaryColor, toolbarAreaTheme, chatAreaTheme, messageAreaTheme, preChatTheme, avatarTheme)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      primaryColor,
      toolbarAreaTheme,
      chatAreaTheme,
      messageAreaTheme,
      preChatTheme,
      avatarTheme,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class FlutterMessagePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BrandingTypeMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfigurationMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AvatarThemeMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageAreaThemeMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ChatAreaThemeMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreChatThemeMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ToolbarAreaThemeMessage.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ThemeMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BrandingTypeMessage -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is ConfigurationMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is UserMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AvatarThemeMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MessageAreaThemeMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ChatAreaThemeMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PreChatThemeMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ToolbarAreaThemeMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ThemeMessage -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterHelpCrunchApi {
  fun initialize(configuration: ConfigurationMessage, user: UserMessage, theme: ThemeMessage?)
  fun updateUser(user: UserMessage)
  fun showChatScreen(): Boolean
  fun sendMessage(message: String, isForceNewChat: Boolean)
  fun logout()

  companion object {
    /** The codec used by FlutterHelpCrunchApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterMessagePigeonCodec()
    }
    /** Sets up an instance of `FlutterHelpCrunchApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterHelpCrunchApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as ConfigurationMessage
            val userArg = args[1] as UserMessage
            val themeArg = args[2] as ThemeMessage?
            val wrapped: List<Any?> = try {
              api.initialize(configurationArg, userArg, themeArg)
              listOf(null)
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.updateUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val userArg = args[0] as UserMessage
            val wrapped: List<Any?> = try {
              api.updateUser(userArg)
              listOf(null)
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.showChatScreen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.showChatScreen())
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.sendMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val isForceNewChatArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.sendMessage(messageArg, isForceNewChatArg)
              listOf(null)
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.logout()
              listOf(null)
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
