// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object FlutterMessagePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class BrandingTypeMessage(val raw: Int) {
  LIGHT(0),
  DARK(1);

  companion object {
    fun ofRaw(raw: Int): BrandingTypeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConfigurationMessage (
  val organization: String,
  val applicationId: String,
  val applicationSecret: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfigurationMessage {
      val organization = pigeonVar_list[0] as String
      val applicationId = pigeonVar_list[1] as String
      val applicationSecret = pigeonVar_list[2] as String
      return ConfigurationMessage(organization, applicationId, applicationSecret)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      organization,
      applicationId,
      applicationSecret,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ConfigurationMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UserMessage (
  val id: String,
  val name: String? = null,
  val email: String? = null,
  val phone: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserMessage {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val email = pigeonVar_list[2] as String?
      val phone = pigeonVar_list[3] as String?
      return UserMessage(id, name, email, phone)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      email,
      phone,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AvatarThemeMessage (
  val useDefaultAvatarColors: Boolean,
  val placeholderBackgroundColorHex: String? = null,
  val placeholderTextColorHex: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AvatarThemeMessage {
      val useDefaultAvatarColors = pigeonVar_list[0] as Boolean
      val placeholderBackgroundColorHex = pigeonVar_list[1] as String?
      val placeholderTextColorHex = pigeonVar_list[2] as String?
      return AvatarThemeMessage(useDefaultAvatarColors, placeholderBackgroundColorHex, placeholderTextColorHex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      useDefaultAvatarColors,
      placeholderBackgroundColorHex,
      placeholderTextColorHex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AvatarThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MessageAreaThemeMessage (
  val backgroundColorHex: String? = null,
  val inputOutlineColorHex: String? = null,
  val inputFieldTextColorHex: String? = null,
  val inputFieldTextHintColorHex: String? = null,
  val messageMenuBackgroundColorHex: String? = null,
  val messageMenuTextColorHex: String? = null,
  val messageMenuSummaryTextColorHex: String? = null,
  val messageMenuIconColorHex: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageAreaThemeMessage {
      val backgroundColorHex = pigeonVar_list[0] as String?
      val inputOutlineColorHex = pigeonVar_list[1] as String?
      val inputFieldTextColorHex = pigeonVar_list[2] as String?
      val inputFieldTextHintColorHex = pigeonVar_list[3] as String?
      val messageMenuBackgroundColorHex = pigeonVar_list[4] as String?
      val messageMenuTextColorHex = pigeonVar_list[5] as String?
      val messageMenuSummaryTextColorHex = pigeonVar_list[6] as String?
      val messageMenuIconColorHex = pigeonVar_list[7] as String?
      return MessageAreaThemeMessage(backgroundColorHex, inputOutlineColorHex, inputFieldTextColorHex, inputFieldTextHintColorHex, messageMenuBackgroundColorHex, messageMenuTextColorHex, messageMenuSummaryTextColorHex, messageMenuIconColorHex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      backgroundColorHex,
      inputOutlineColorHex,
      inputFieldTextColorHex,
      inputFieldTextHintColorHex,
      messageMenuBackgroundColorHex,
      messageMenuTextColorHex,
      messageMenuSummaryTextColorHex,
      messageMenuIconColorHex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MessageAreaThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ChatAreaThemeMessage (
  val incomingBubbleTextColorHex: String? = null,
  val outcomingBubbleTextColorHex: String? = null,
  val incomingBubbleColorHex: String? = null,
  val outcomingBubbleColorHex: String? = null,
  val backgroundColorHex: String? = null,
  val brandingType: BrandingTypeMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ChatAreaThemeMessage {
      val incomingBubbleTextColorHex = pigeonVar_list[0] as String?
      val outcomingBubbleTextColorHex = pigeonVar_list[1] as String?
      val incomingBubbleColorHex = pigeonVar_list[2] as String?
      val outcomingBubbleColorHex = pigeonVar_list[3] as String?
      val backgroundColorHex = pigeonVar_list[4] as String?
      val brandingType = pigeonVar_list[5] as BrandingTypeMessage
      return ChatAreaThemeMessage(incomingBubbleTextColorHex, outcomingBubbleTextColorHex, incomingBubbleColorHex, outcomingBubbleColorHex, backgroundColorHex, brandingType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      incomingBubbleTextColorHex,
      outcomingBubbleTextColorHex,
      incomingBubbleColorHex,
      outcomingBubbleColorHex,
      backgroundColorHex,
      brandingType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ChatAreaThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SystemAlertsThemeMessage (
  val dialogsHeaderColorHex: String? = null,
  val toastsBackgroundColorHex: String? = null,
  val toastsTextColorHex: String? = null,
  val welcomeMessageBackgroundColorHex: String? = null,
  val welcomeMessageTextColorHex: String? = null,
  val warningDialogsHeaderColorHex: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SystemAlertsThemeMessage {
      val dialogsHeaderColorHex = pigeonVar_list[0] as String?
      val toastsBackgroundColorHex = pigeonVar_list[1] as String?
      val toastsTextColorHex = pigeonVar_list[2] as String?
      val welcomeMessageBackgroundColorHex = pigeonVar_list[3] as String?
      val welcomeMessageTextColorHex = pigeonVar_list[4] as String?
      val warningDialogsHeaderColorHex = pigeonVar_list[5] as String?
      return SystemAlertsThemeMessage(dialogsHeaderColorHex, toastsBackgroundColorHex, toastsTextColorHex, welcomeMessageBackgroundColorHex, welcomeMessageTextColorHex, warningDialogsHeaderColorHex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dialogsHeaderColorHex,
      toastsBackgroundColorHex,
      toastsTextColorHex,
      welcomeMessageBackgroundColorHex,
      welcomeMessageTextColorHex,
      warningDialogsHeaderColorHex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SystemAlertsThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreChatThemeMessage (
  val inputFieldTextColorHex: String? = null,
  val inputFieldTextHintColorHex: String? = null,
  val backgroundColorHex: String? = null,
  val messageBackgroundColorHex: String? = null,
  val messageTextColorHex: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreChatThemeMessage {
      val inputFieldTextColorHex = pigeonVar_list[0] as String?
      val inputFieldTextHintColorHex = pigeonVar_list[1] as String?
      val backgroundColorHex = pigeonVar_list[2] as String?
      val messageBackgroundColorHex = pigeonVar_list[3] as String?
      val messageTextColorHex = pigeonVar_list[4] as String?
      return PreChatThemeMessage(inputFieldTextColorHex, inputFieldTextHintColorHex, backgroundColorHex, messageBackgroundColorHex, messageTextColorHex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      inputFieldTextColorHex,
      inputFieldTextHintColorHex,
      backgroundColorHex,
      messageBackgroundColorHex,
      messageTextColorHex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PreChatThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ToolbarAreaThemeMessage (
  val backgroundColorHex: String? = null,
  val statusBarColorHex: String? = null,
  val outlineColorHex: String? = null,
  val agentsTextColorHex: String? = null,
  val avatarTheme: AvatarThemeMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ToolbarAreaThemeMessage {
      val backgroundColorHex = pigeonVar_list[0] as String?
      val statusBarColorHex = pigeonVar_list[1] as String?
      val outlineColorHex = pigeonVar_list[2] as String?
      val agentsTextColorHex = pigeonVar_list[3] as String?
      val avatarTheme = pigeonVar_list[4] as AvatarThemeMessage?
      return ToolbarAreaThemeMessage(backgroundColorHex, statusBarColorHex, outlineColorHex, agentsTextColorHex, avatarTheme)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      backgroundColorHex,
      statusBarColorHex,
      outlineColorHex,
      agentsTextColorHex,
      avatarTheme,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ToolbarAreaThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ThemeMessage (
  val primaryColorHex: String? = null,
  val toolbarAreaTheme: ToolbarAreaThemeMessage? = null,
  val chatAreaTheme: ChatAreaThemeMessage? = null,
  val messageAreaTheme: MessageAreaThemeMessage? = null,
  val preChatTheme: PreChatThemeMessage? = null,
  val systemAlertsTheme: SystemAlertsThemeMessage? = null,
  val avatarTheme: AvatarThemeMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ThemeMessage {
      val primaryColorHex = pigeonVar_list[0] as String?
      val toolbarAreaTheme = pigeonVar_list[1] as ToolbarAreaThemeMessage?
      val chatAreaTheme = pigeonVar_list[2] as ChatAreaThemeMessage?
      val messageAreaTheme = pigeonVar_list[3] as MessageAreaThemeMessage?
      val preChatTheme = pigeonVar_list[4] as PreChatThemeMessage?
      val systemAlertsTheme = pigeonVar_list[5] as SystemAlertsThemeMessage?
      val avatarTheme = pigeonVar_list[6] as AvatarThemeMessage?
      return ThemeMessage(primaryColorHex, toolbarAreaTheme, chatAreaTheme, messageAreaTheme, preChatTheme, systemAlertsTheme, avatarTheme)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      primaryColorHex,
      toolbarAreaTheme,
      chatAreaTheme,
      messageAreaTheme,
      preChatTheme,
      systemAlertsTheme,
      avatarTheme,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ThemeMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return FlutterMessagePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class FlutterMessagePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BrandingTypeMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfigurationMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AvatarThemeMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageAreaThemeMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ChatAreaThemeMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SystemAlertsThemeMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreChatThemeMessage.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ToolbarAreaThemeMessage.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ThemeMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BrandingTypeMessage -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is ConfigurationMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is UserMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AvatarThemeMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MessageAreaThemeMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ChatAreaThemeMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is SystemAlertsThemeMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PreChatThemeMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ToolbarAreaThemeMessage -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ThemeMessage -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterHelpCrunchApi {
  fun initialize(configuration: ConfigurationMessage, user: UserMessage, theme: ThemeMessage?)
  fun updateUser(user: UserMessage)
  fun showChatScreen(): Boolean
  fun sendMessage(message: String, isForceNewChat: Boolean)
  fun logout()

  companion object {
    /** The codec used by FlutterHelpCrunchApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterMessagePigeonCodec()
    }
    /** Sets up an instance of `FlutterHelpCrunchApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterHelpCrunchApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configurationArg = args[0] as ConfigurationMessage
            val userArg = args[1] as UserMessage
            val themeArg = args[2] as ThemeMessage?
            val wrapped: List<Any?> = try {
              api.initialize(configurationArg, userArg, themeArg)
              listOf(null)
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.updateUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val userArg = args[0] as UserMessage
            val wrapped: List<Any?> = try {
              api.updateUser(userArg)
              listOf(null)
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.showChatScreen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.showChatScreen())
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.sendMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val isForceNewChatArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.sendMessage(messageArg, isForceNewChatArg)
              listOf(null)
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.logout()
              listOf(null)
            } catch (exception: Throwable) {
              FlutterMessagePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
