// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum BrandingTypeMessage {
  light,
  dark,
}

class ConfigurationMessage {
  ConfigurationMessage({
    required this.organization,
    required this.applicationId,
    required this.applicationSecret,
  });

  String organization;

  String applicationId;

  String applicationSecret;

  List<Object?> _toList() {
    return <Object?>[
      organization,
      applicationId,
      applicationSecret,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConfigurationMessage decode(Object result) {
    result as List<Object?>;
    return ConfigurationMessage(
      organization: result[0]! as String,
      applicationId: result[1]! as String,
      applicationSecret: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConfigurationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class UserMessage {
  UserMessage({
    required this.id,
    this.name,
    this.email,
    this.phone,
  });

  String id;

  String? name;

  String? email;

  String? phone;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      email,
      phone,
    ];
  }

  Object encode() {
    return _toList();  }

  static UserMessage decode(Object result) {
    result as List<Object?>;
    return UserMessage(
      id: result[0]! as String,
      name: result[1] as String?,
      email: result[2] as String?,
      phone: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UserMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AvatarThemeMessage {
  AvatarThemeMessage({
    required this.useDefaultAvatarColors,
    this.placeholderBackgroundColorHex,
    this.placeholderTextColorHex,
  });

  bool useDefaultAvatarColors;

  String? placeholderBackgroundColorHex;

  String? placeholderTextColorHex;

  List<Object?> _toList() {
    return <Object?>[
      useDefaultAvatarColors,
      placeholderBackgroundColorHex,
      placeholderTextColorHex,
    ];
  }

  Object encode() {
    return _toList();  }

  static AvatarThemeMessage decode(Object result) {
    result as List<Object?>;
    return AvatarThemeMessage(
      useDefaultAvatarColors: result[0]! as bool,
      placeholderBackgroundColorHex: result[1] as String?,
      placeholderTextColorHex: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AvatarThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class MessageAreaThemeMessage {
  MessageAreaThemeMessage({
    this.backgroundColorHex,
    this.inputOutlineColorHex,
    this.inputFieldTextColorHex,
    this.inputFieldTextHintColorHex,
    this.messageMenuBackgroundColorHex,
    this.messageMenuTextColorHex,
    this.messageMenuSummaryTextColorHex,
    this.messageMenuIconColorHex,
  });

  String? backgroundColorHex;

  String? inputOutlineColorHex;

  String? inputFieldTextColorHex;

  String? inputFieldTextHintColorHex;

  String? messageMenuBackgroundColorHex;

  String? messageMenuTextColorHex;

  String? messageMenuSummaryTextColorHex;

  String? messageMenuIconColorHex;

  List<Object?> _toList() {
    return <Object?>[
      backgroundColorHex,
      inputOutlineColorHex,
      inputFieldTextColorHex,
      inputFieldTextHintColorHex,
      messageMenuBackgroundColorHex,
      messageMenuTextColorHex,
      messageMenuSummaryTextColorHex,
      messageMenuIconColorHex,
    ];
  }

  Object encode() {
    return _toList();  }

  static MessageAreaThemeMessage decode(Object result) {
    result as List<Object?>;
    return MessageAreaThemeMessage(
      backgroundColorHex: result[0] as String?,
      inputOutlineColorHex: result[1] as String?,
      inputFieldTextColorHex: result[2] as String?,
      inputFieldTextHintColorHex: result[3] as String?,
      messageMenuBackgroundColorHex: result[4] as String?,
      messageMenuTextColorHex: result[5] as String?,
      messageMenuSummaryTextColorHex: result[6] as String?,
      messageMenuIconColorHex: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MessageAreaThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ChatAreaThemeMessage {
  ChatAreaThemeMessage({
    this.incomingBubbleTextColorHex,
    this.outcomingBubbleTextColorHex,
    this.incomingBubbleColorHex,
    this.outcomingBubbleColorHex,
    this.backgroundColorHex,
    required this.brandingType,
  });

  String? incomingBubbleTextColorHex;

  String? outcomingBubbleTextColorHex;

  String? incomingBubbleColorHex;

  String? outcomingBubbleColorHex;

  String? backgroundColorHex;

  BrandingTypeMessage brandingType;

  List<Object?> _toList() {
    return <Object?>[
      incomingBubbleTextColorHex,
      outcomingBubbleTextColorHex,
      incomingBubbleColorHex,
      outcomingBubbleColorHex,
      backgroundColorHex,
      brandingType,
    ];
  }

  Object encode() {
    return _toList();  }

  static ChatAreaThemeMessage decode(Object result) {
    result as List<Object?>;
    return ChatAreaThemeMessage(
      incomingBubbleTextColorHex: result[0] as String?,
      outcomingBubbleTextColorHex: result[1] as String?,
      incomingBubbleColorHex: result[2] as String?,
      outcomingBubbleColorHex: result[3] as String?,
      backgroundColorHex: result[4] as String?,
      brandingType: result[5]! as BrandingTypeMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ChatAreaThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SystemAlertsThemeMessage {
  SystemAlertsThemeMessage({
    this.dialogsHeaderColorHex,
    this.toastsBackgroundColorHex,
    this.toastsTextColorHex,
    this.welcomeMessageBackgroundColorHex,
    this.welcomeMessageTextColorHex,
    this.warningDialogsHeaderColorHex,
  });

  String? dialogsHeaderColorHex;

  String? toastsBackgroundColorHex;

  String? toastsTextColorHex;

  String? welcomeMessageBackgroundColorHex;

  String? welcomeMessageTextColorHex;

  String? warningDialogsHeaderColorHex;

  List<Object?> _toList() {
    return <Object?>[
      dialogsHeaderColorHex,
      toastsBackgroundColorHex,
      toastsTextColorHex,
      welcomeMessageBackgroundColorHex,
      welcomeMessageTextColorHex,
      warningDialogsHeaderColorHex,
    ];
  }

  Object encode() {
    return _toList();  }

  static SystemAlertsThemeMessage decode(Object result) {
    result as List<Object?>;
    return SystemAlertsThemeMessage(
      dialogsHeaderColorHex: result[0] as String?,
      toastsBackgroundColorHex: result[1] as String?,
      toastsTextColorHex: result[2] as String?,
      welcomeMessageBackgroundColorHex: result[3] as String?,
      welcomeMessageTextColorHex: result[4] as String?,
      warningDialogsHeaderColorHex: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SystemAlertsThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class PreChatThemeMessage {
  PreChatThemeMessage({
    this.inputFieldTextColorHex,
    this.inputFieldTextHintColorHex,
    this.backgroundColorHex,
    this.messageBackgroundColorHex,
    this.messageTextColorHex,
  });

  String? inputFieldTextColorHex;

  String? inputFieldTextHintColorHex;

  String? backgroundColorHex;

  String? messageBackgroundColorHex;

  String? messageTextColorHex;

  List<Object?> _toList() {
    return <Object?>[
      inputFieldTextColorHex,
      inputFieldTextHintColorHex,
      backgroundColorHex,
      messageBackgroundColorHex,
      messageTextColorHex,
    ];
  }

  Object encode() {
    return _toList();  }

  static PreChatThemeMessage decode(Object result) {
    result as List<Object?>;
    return PreChatThemeMessage(
      inputFieldTextColorHex: result[0] as String?,
      inputFieldTextHintColorHex: result[1] as String?,
      backgroundColorHex: result[2] as String?,
      messageBackgroundColorHex: result[3] as String?,
      messageTextColorHex: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreChatThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ToolbarAreaThemeMessage {
  ToolbarAreaThemeMessage({
    this.backgroundColorHex,
    this.statusBarColorHex,
    this.outlineColorHex,
    this.agentsTextColorHex,
    this.avatarTheme,
  });

  String? backgroundColorHex;

  String? statusBarColorHex;

  String? outlineColorHex;

  String? agentsTextColorHex;

  AvatarThemeMessage? avatarTheme;

  List<Object?> _toList() {
    return <Object?>[
      backgroundColorHex,
      statusBarColorHex,
      outlineColorHex,
      agentsTextColorHex,
      avatarTheme,
    ];
  }

  Object encode() {
    return _toList();  }

  static ToolbarAreaThemeMessage decode(Object result) {
    result as List<Object?>;
    return ToolbarAreaThemeMessage(
      backgroundColorHex: result[0] as String?,
      statusBarColorHex: result[1] as String?,
      outlineColorHex: result[2] as String?,
      agentsTextColorHex: result[3] as String?,
      avatarTheme: result[4] as AvatarThemeMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ToolbarAreaThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ThemeMessage {
  ThemeMessage({
    this.primaryColorHex,
    this.toolbarAreaTheme,
    this.chatAreaTheme,
    this.messageAreaTheme,
    this.preChatTheme,
    this.systemAlertsTheme,
    this.avatarTheme,
  });

  String? primaryColorHex;

  ToolbarAreaThemeMessage? toolbarAreaTheme;

  ChatAreaThemeMessage? chatAreaTheme;

  MessageAreaThemeMessage? messageAreaTheme;

  PreChatThemeMessage? preChatTheme;

  SystemAlertsThemeMessage? systemAlertsTheme;

  AvatarThemeMessage? avatarTheme;

  List<Object?> _toList() {
    return <Object?>[
      primaryColorHex,
      toolbarAreaTheme,
      chatAreaTheme,
      messageAreaTheme,
      preChatTheme,
      systemAlertsTheme,
      avatarTheme,
    ];
  }

  Object encode() {
    return _toList();  }

  static ThemeMessage decode(Object result) {
    result as List<Object?>;
    return ThemeMessage(
      primaryColorHex: result[0] as String?,
      toolbarAreaTheme: result[1] as ToolbarAreaThemeMessage?,
      chatAreaTheme: result[2] as ChatAreaThemeMessage?,
      messageAreaTheme: result[3] as MessageAreaThemeMessage?,
      preChatTheme: result[4] as PreChatThemeMessage?,
      systemAlertsTheme: result[5] as SystemAlertsThemeMessage?,
      avatarTheme: result[6] as AvatarThemeMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BrandingTypeMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ConfigurationMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is UserMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AvatarThemeMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is MessageAreaThemeMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ChatAreaThemeMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is SystemAlertsThemeMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PreChatThemeMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is ToolbarAreaThemeMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is ThemeMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BrandingTypeMessage.values[value];
      case 130: 
        return ConfigurationMessage.decode(readValue(buffer)!);
      case 131: 
        return UserMessage.decode(readValue(buffer)!);
      case 132: 
        return AvatarThemeMessage.decode(readValue(buffer)!);
      case 133: 
        return MessageAreaThemeMessage.decode(readValue(buffer)!);
      case 134: 
        return ChatAreaThemeMessage.decode(readValue(buffer)!);
      case 135: 
        return SystemAlertsThemeMessage.decode(readValue(buffer)!);
      case 136: 
        return PreChatThemeMessage.decode(readValue(buffer)!);
      case 137: 
        return ToolbarAreaThemeMessage.decode(readValue(buffer)!);
      case 138: 
        return ThemeMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FlutterHelpCrunchApi {
  /// Constructor for [FlutterHelpCrunchApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterHelpCrunchApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize({required ConfigurationMessage configuration, required UserMessage user, ThemeMessage? theme, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[configuration, user, theme]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateUser({required UserMessage user}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.updateUser$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[user]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> showChatScreen() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.showChatScreen$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> sendMessage({required String message, required bool isForceNewChat}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.sendMessage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message, isForceNewChat]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> logout() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.logout$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
