// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum BrandingTypeMessage {
  light,
  dark,
}

class ConfigurationMessage {
  ConfigurationMessage({
    required this.organization,
    required this.applicationId,
    required this.applicationSecret,
  });

  String organization;

  int applicationId;

  String applicationSecret;

  List<Object?> _toList() {
    return <Object?>[
      organization,
      applicationId,
      applicationSecret,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConfigurationMessage decode(Object result) {
    result as List<Object?>;
    return ConfigurationMessage(
      organization: result[0]! as String,
      applicationId: result[1]! as int,
      applicationSecret: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConfigurationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class UserMessage {
  UserMessage({
    required this.id,
    this.name,
    this.email,
    this.phone,
  });

  String id;

  String? name;

  String? email;

  String? phone;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      email,
      phone,
    ];
  }

  Object encode() {
    return _toList();  }

  static UserMessage decode(Object result) {
    result as List<Object?>;
    return UserMessage(
      id: result[0]! as String,
      name: result[1] as String?,
      email: result[2] as String?,
      phone: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UserMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class AvatarThemeMessage {
  AvatarThemeMessage({
    required this.useDefaultAvatarColors,
    this.placeholderBackgroundColor,
    this.placeholderTextColor,
  });

  bool useDefaultAvatarColors;

  int? placeholderBackgroundColor;

  int? placeholderTextColor;

  List<Object?> _toList() {
    return <Object?>[
      useDefaultAvatarColors,
      placeholderBackgroundColor,
      placeholderTextColor,
    ];
  }

  Object encode() {
    return _toList();  }

  static AvatarThemeMessage decode(Object result) {
    result as List<Object?>;
    return AvatarThemeMessage(
      useDefaultAvatarColors: result[0]! as bool,
      placeholderBackgroundColor: result[1] as int?,
      placeholderTextColor: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AvatarThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class MessageAreaThemeMessage {
  MessageAreaThemeMessage({
    this.backgroundColor,
    this.inputOutlineColor,
    this.inputFieldTextColor,
    this.inputFieldTextHintColor,
    this.messageMenuBackgroundColor,
    this.messageMenuTextColor,
    this.messageMenuSummaryTextColor,
    this.messageMenuIconColor,
    this.navigationBarColor,
  });

  int? backgroundColor;

  int? inputOutlineColor;

  int? inputFieldTextColor;

  int? inputFieldTextHintColor;

  int? messageMenuBackgroundColor;

  int? messageMenuTextColor;

  int? messageMenuSummaryTextColor;

  int? messageMenuIconColor;

  int? navigationBarColor;

  List<Object?> _toList() {
    return <Object?>[
      backgroundColor,
      inputOutlineColor,
      inputFieldTextColor,
      inputFieldTextHintColor,
      messageMenuBackgroundColor,
      messageMenuTextColor,
      messageMenuSummaryTextColor,
      messageMenuIconColor,
      navigationBarColor,
    ];
  }

  Object encode() {
    return _toList();  }

  static MessageAreaThemeMessage decode(Object result) {
    result as List<Object?>;
    return MessageAreaThemeMessage(
      backgroundColor: result[0] as int?,
      inputOutlineColor: result[1] as int?,
      inputFieldTextColor: result[2] as int?,
      inputFieldTextHintColor: result[3] as int?,
      messageMenuBackgroundColor: result[4] as int?,
      messageMenuTextColor: result[5] as int?,
      messageMenuSummaryTextColor: result[6] as int?,
      messageMenuIconColor: result[7] as int?,
      navigationBarColor: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MessageAreaThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ChatAreaThemeMessage {
  ChatAreaThemeMessage({
    this.incomingBubbleTextColor,
    this.outcomingBubbleTextColor,
    this.incomingBubbleColor,
    this.outcomingBubbleColor,
    this.backgroundColor,
    required this.brandingType,
    this.incomingCodeBackgroundColor,
    this.outcomingCodeBackgroundColor,
    this.incomingCodeTextColor,
    this.outcomingCodeTextColor,
    this.incomingBlockQuoteColor,
    this.outcomingBlockQuoteColor,
    this.incomingFileTextColor,
    this.outcomingFileTextColor,
    this.authorNameColor,
    this.systemMessageColor,
    this.timeTextColor,
    this.progressViewsColor,
    this.chatBackgroundColor,
    this.incomingBubbleLinkColor,
    this.outcomingBubbleLinkColor,
    this.attachmentIconsColor,
    this.incomingFileBackgroundColor,
    this.outcomingFileBackgroundColor,
    this.incomingFileIconColor,
    this.outcomingFileIconColor,
    this.fabDownBackgroundColor,
    this.fabBatchBackgroundColor,
    this.fabBatchTextColor,
  });

  int? incomingBubbleTextColor;

  int? outcomingBubbleTextColor;

  int? incomingBubbleColor;

  int? outcomingBubbleColor;

  int? backgroundColor;

  BrandingTypeMessage brandingType;

  int? incomingCodeBackgroundColor;

  int? outcomingCodeBackgroundColor;

  int? incomingCodeTextColor;

  int? outcomingCodeTextColor;

  int? incomingBlockQuoteColor;

  int? outcomingBlockQuoteColor;

  int? incomingFileTextColor;

  int? outcomingFileTextColor;

  int? authorNameColor;

  int? systemMessageColor;

  int? timeTextColor;

  int? progressViewsColor;

  int? chatBackgroundColor;

  int? incomingBubbleLinkColor;

  int? outcomingBubbleLinkColor;

  int? attachmentIconsColor;

  int? incomingFileBackgroundColor;

  int? outcomingFileBackgroundColor;

  int? incomingFileIconColor;

  int? outcomingFileIconColor;

  int? fabDownBackgroundColor;

  int? fabBatchBackgroundColor;

  int? fabBatchTextColor;

  List<Object?> _toList() {
    return <Object?>[
      incomingBubbleTextColor,
      outcomingBubbleTextColor,
      incomingBubbleColor,
      outcomingBubbleColor,
      backgroundColor,
      brandingType,
      incomingCodeBackgroundColor,
      outcomingCodeBackgroundColor,
      incomingCodeTextColor,
      outcomingCodeTextColor,
      incomingBlockQuoteColor,
      outcomingBlockQuoteColor,
      incomingFileTextColor,
      outcomingFileTextColor,
      authorNameColor,
      systemMessageColor,
      timeTextColor,
      progressViewsColor,
      chatBackgroundColor,
      incomingBubbleLinkColor,
      outcomingBubbleLinkColor,
      attachmentIconsColor,
      incomingFileBackgroundColor,
      outcomingFileBackgroundColor,
      incomingFileIconColor,
      outcomingFileIconColor,
      fabDownBackgroundColor,
      fabBatchBackgroundColor,
      fabBatchTextColor,
    ];
  }

  Object encode() {
    return _toList();  }

  static ChatAreaThemeMessage decode(Object result) {
    result as List<Object?>;
    return ChatAreaThemeMessage(
      incomingBubbleTextColor: result[0] as int?,
      outcomingBubbleTextColor: result[1] as int?,
      incomingBubbleColor: result[2] as int?,
      outcomingBubbleColor: result[3] as int?,
      backgroundColor: result[4] as int?,
      brandingType: result[5]! as BrandingTypeMessage,
      incomingCodeBackgroundColor: result[6] as int?,
      outcomingCodeBackgroundColor: result[7] as int?,
      incomingCodeTextColor: result[8] as int?,
      outcomingCodeTextColor: result[9] as int?,
      incomingBlockQuoteColor: result[10] as int?,
      outcomingBlockQuoteColor: result[11] as int?,
      incomingFileTextColor: result[12] as int?,
      outcomingFileTextColor: result[13] as int?,
      authorNameColor: result[14] as int?,
      systemMessageColor: result[15] as int?,
      timeTextColor: result[16] as int?,
      progressViewsColor: result[17] as int?,
      chatBackgroundColor: result[18] as int?,
      incomingBubbleLinkColor: result[19] as int?,
      outcomingBubbleLinkColor: result[20] as int?,
      attachmentIconsColor: result[21] as int?,
      incomingFileBackgroundColor: result[22] as int?,
      outcomingFileBackgroundColor: result[23] as int?,
      incomingFileIconColor: result[24] as int?,
      outcomingFileIconColor: result[25] as int?,
      fabDownBackgroundColor: result[26] as int?,
      fabBatchBackgroundColor: result[27] as int?,
      fabBatchTextColor: result[28] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ChatAreaThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class PreChatThemeMessage {
  PreChatThemeMessage({
    this.inputFieldTextColor,
    this.inputFieldTextHintColor,
    this.backgroundColor,
    this.messageBackgroundColor,
    this.messageTextColor,
    this.gdprLinkTextColor,
  });

  int? inputFieldTextColor;

  int? inputFieldTextHintColor;

  int? backgroundColor;

  int? messageBackgroundColor;

  int? messageTextColor;

  int? gdprLinkTextColor;

  List<Object?> _toList() {
    return <Object?>[
      inputFieldTextColor,
      inputFieldTextHintColor,
      backgroundColor,
      messageBackgroundColor,
      messageTextColor,
      gdprLinkTextColor,
    ];
  }

  Object encode() {
    return _toList();  }

  static PreChatThemeMessage decode(Object result) {
    result as List<Object?>;
    return PreChatThemeMessage(
      inputFieldTextColor: result[0] as int?,
      inputFieldTextHintColor: result[1] as int?,
      backgroundColor: result[2] as int?,
      messageBackgroundColor: result[3] as int?,
      messageTextColor: result[4] as int?,
      gdprLinkTextColor: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreChatThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ToolbarAreaThemeMessage {
  ToolbarAreaThemeMessage({
    this.backgroundColor,
    this.statusBarColor,
    this.outlineColor,
    this.agentsTextColor,
  });

  int? backgroundColor;

  int? statusBarColor;

  int? outlineColor;

  int? agentsTextColor;

  List<Object?> _toList() {
    return <Object?>[
      backgroundColor,
      statusBarColor,
      outlineColor,
      agentsTextColor,
    ];
  }

  Object encode() {
    return _toList();  }

  static ToolbarAreaThemeMessage decode(Object result) {
    result as List<Object?>;
    return ToolbarAreaThemeMessage(
      backgroundColor: result[0] as int?,
      statusBarColor: result[1] as int?,
      outlineColor: result[2] as int?,
      agentsTextColor: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ToolbarAreaThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ThemeMessage {
  ThemeMessage({
    this.primaryColor,
    this.toolbarAreaTheme,
    this.chatAreaTheme,
    this.messageAreaTheme,
    this.preChatTheme,
    this.avatarTheme,
  });

  int? primaryColor;

  ToolbarAreaThemeMessage? toolbarAreaTheme;

  ChatAreaThemeMessage? chatAreaTheme;

  MessageAreaThemeMessage? messageAreaTheme;

  PreChatThemeMessage? preChatTheme;

  AvatarThemeMessage? avatarTheme;

  List<Object?> _toList() {
    return <Object?>[
      primaryColor,
      toolbarAreaTheme,
      chatAreaTheme,
      messageAreaTheme,
      preChatTheme,
      avatarTheme,
    ];
  }

  Object encode() {
    return _toList();  }

  static ThemeMessage decode(Object result) {
    result as List<Object?>;
    return ThemeMessage(
      primaryColor: result[0] as int?,
      toolbarAreaTheme: result[1] as ToolbarAreaThemeMessage?,
      chatAreaTheme: result[2] as ChatAreaThemeMessage?,
      messageAreaTheme: result[3] as MessageAreaThemeMessage?,
      preChatTheme: result[4] as PreChatThemeMessage?,
      avatarTheme: result[5] as AvatarThemeMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ThemeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BrandingTypeMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ConfigurationMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is UserMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AvatarThemeMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is MessageAreaThemeMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ChatAreaThemeMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PreChatThemeMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is ToolbarAreaThemeMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is ThemeMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final value = readValue(buffer) as int?;
        return value == null ? null : BrandingTypeMessage.values[value];
      case 130: 
        return ConfigurationMessage.decode(readValue(buffer)!);
      case 131: 
        return UserMessage.decode(readValue(buffer)!);
      case 132: 
        return AvatarThemeMessage.decode(readValue(buffer)!);
      case 133: 
        return MessageAreaThemeMessage.decode(readValue(buffer)!);
      case 134: 
        return ChatAreaThemeMessage.decode(readValue(buffer)!);
      case 135: 
        return PreChatThemeMessage.decode(readValue(buffer)!);
      case 136: 
        return ToolbarAreaThemeMessage.decode(readValue(buffer)!);
      case 137: 
        return ThemeMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FlutterHelpCrunchApi {
  /// Constructor for [FlutterHelpCrunchApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterHelpCrunchApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize({required ConfigurationMessage configuration, required UserMessage user, ThemeMessage? theme, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[configuration, user, theme]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateUser({required UserMessage user}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.updateUser$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[user]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> showChatScreen() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.showChatScreen$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> sendMessage({required String message, required bool isForceNewChat}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.sendMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[message, isForceNewChat]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> logout() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_help_crunch.FlutterHelpCrunchApi.logout$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
